// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("3.6.27.1056")]
[assembly: AssemblyFileVersion("3.6.27.1056")]
